-- Backup for export_shipments
-- 1 records
-- Generated: 2025-10-09T16:04:26.369Z

INSERT INTO export_shipments ("id", "jobRef", "jobType", "createdAt", "createdBy", "status", "receiverId", "destinationCustomerId", "jobContactName", "jobContactEmail", "customerReferenceNumber", "bookingDate", "collectionDate", "dispatchDate", "etaPortDate", "deliveryDate", "deliveryTime", "deliveryReference", "deliveryTimeNotes", "proofOfDelivery", "trailerNo", "departureFrom", "portOfArrival", "incoterms", "containerShipment", "vesselName", "exportClearanceAgent", "arrivalClearanceAgent", "supplier", "consignee", "value", "numberOfPieces", "packaging", "goodsDescription", "weight", "cube", "freightRateOut", "clearanceCharge", "arrivalClearanceCost", "currency", "additionalCommodityCodes", "additionalCommodityCodeCharge", "currencyIn", "haulierFreightRateIn", "exportClearanceChargeIn", "destinationClearanceCostIn", "expensesToChargeOut", "additionalExpensesIn", "haulierName", "haulierContactName", "haulierEmail", "haulierTelephone", "haulierReference", "deliveryAddress", "clearanceType", "clearanceAgent", "mrn", "collectionAddress", "collectionContactName", "collectionContactTelephone", "collectionContactEmail", "collectionReference", "collectionNotes", "additionalNotes", "jobTags", "attachments", "linkedClearanceId", "bookJobWithHaulierStatusIndicator", "bookJobWithHaulierStatusIndicatorTimestamp", "adviseClearanceToAgentStatusIndicator", "adviseClearanceToAgentStatusIndicatorTimestamp", "sendHaulierEadStatusIndicator", "sendHaulierEadStatusIndicatorTimestamp", "invoiceCustomerStatusIndicator", "invoiceCustomerStatusIndicatorTimestamp", "sendPodToCustomerStatusIndicator", "sendPodToCustomerStatusIndicatorTimestamp") VALUES ('71248d19-dd47-4f44-b7bc-9b538ba2532a', 26003, 'export', '2025-10-07T13:03:01.990Z', NULL, 'Dispatched', '8da94cf5-5392-4842-ae41-981cdb1c93b0', 'd49f7951-bcf0-4639-9dd4-fe861aaeaaa1', ARRAY["efewf"], ARRAY["wefwfe@weff.com"], '879867868', '10/07/25', '2025-10-09', '2025-10-10', NULL, NULL, NULL, '', '', ARRAY[], '432424', 'London', 'Istanbul', 'CIP', 'Road Shipment', '', 'R.S', 'Haulier', '', '', '1234', '21', 'Pallets', 'Stuff', '2124', NULL, '1500', '', '55', 'GBP', 1, NULL, NULL, '1200', '45', '', ARRAY[], ARRAY[], 'Emy Logistics', ARRAY["Baris Genc","Meral Kaya"], ARRAY["baris.genc@emylogistics.co.uk","meral.kaya@emylogistics.com"], '', 'Haulier Ref 2', 'Kosmonavtov St.4,
Krasnodar Region,
Kushechevskaya Village,
352030, Russia', 'Export', 'GLB Customs Ltd', NULL, '', '', '', '', '', '', '', ARRAY[], ARRAY[], '6c48551c-8fdc-4281-a6fa-286c7336b2a5', 1, NULL, 3, '2025-10-09T09:27:58.206Z', 1, NULL, 3, '2025-10-09T07:34:44.144Z', 3, '2025-10-09T07:34:45.791Z');

