CREATE TABLE "custom_clearances" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_ref" integer NOT NULL,
	"job_type" text NOT NULL,
	"created_at" text DEFAULT CURRENT_DATE NOT NULL,
	"status" text DEFAULT 'Waiting Entry' NOT NULL,
	"import_customer_id" varchar,
	"export_customer_id" varchar,
	"receiver_id" varchar,
	"eta_port" text,
	"port_of_arrival" text,
	"trailer_or_container_number" text,
	"departure_from" text,
	"container_shipment" boolean DEFAULT false,
	"vessel_name" text,
	"number_of_pieces" text,
	"packaging" text,
	"weight" text,
	"cube" text,
	"goods_description" text,
	"invoice_value" text,
	"transport_costs" text,
	"clearance_charge" text,
	"currency" text,
	"additional_commodity_codes" integer,
	"vat_zero_rated" boolean DEFAULT false,
	"clearance_type" text,
	"incoterms" text,
	"customer_reference_number" text,
	"supplier_name" text,
	"attachments" text,
	"created_from_type" text,
	"created_from_id" varchar
);
--> statement-breakpoint
CREATE TABLE "export_customers" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_name" text NOT NULL,
	"contact_name" text,
	"vat_number" text,
	"telephone" text,
	"fax" text,
	"email" text,
	"address_line_1" text,
	"address_line_2" text,
	"town" text,
	"county" text,
	"postcode" text,
	"country" text,
	"agent_name" text,
	"agent_contact_name" text,
	"agent_telephone" text,
	"agent_fax" text,
	"agent_email" text,
	"agent_address_line_1" text,
	"agent_address_line_2" text,
	"agent_town" text,
	"agent_county" text,
	"agent_postcode" text,
	"agent_country" text
);
--> statement-breakpoint
CREATE TABLE "export_receivers" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_name" text NOT NULL,
	"address_line_1" text,
	"address_line_2" text,
	"town" text,
	"county" text,
	"postcode" text,
	"country" text
);
--> statement-breakpoint
CREATE TABLE "export_shipments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_ref" integer NOT NULL,
	"job_type" text DEFAULT 'export' NOT NULL,
	"created_at" text DEFAULT CURRENT_DATE NOT NULL,
	"status" text DEFAULT 'Pending' NOT NULL,
	"receiver_id" varchar,
	"destination_customer_id" varchar,
	"customer_reference_number" text,
	"load_date" text,
	"trailer_no" text,
	"departure_from" text,
	"port_of_arrival" text,
	"incoterms" text,
	"container_shipment" boolean DEFAULT false,
	"vessel_name" text,
	"export_clearance_agent" text NOT NULL,
	"arrival_clearance_agent" text NOT NULL,
	"supplier" text,
	"consignee" text,
	"value" text,
	"number_of_pieces" text,
	"packaging" text,
	"goods_description" text,
	"weight" text,
	"cube" text,
	"freight_rate_out" text,
	"clearance_charge" text,
	"arrival_clearance_cost" text,
	"currency" text,
	"additional_commodity_codes" integer,
	"haulier_name" text,
	"haulier_contact_name" text,
	"attachments" text
);
--> statement-breakpoint
CREATE TABLE "import_customers" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_name" text NOT NULL,
	"contact_name" text,
	"vat_number" text,
	"telephone" text,
	"fax" text,
	"email" text,
	"address_line_1" text,
	"address_line_2" text,
	"town" text,
	"county" text,
	"postcode" text,
	"country" text,
	"agent_name" text,
	"agent_contact_name" text,
	"agent_telephone" text,
	"agent_fax" text,
	"agent_email" text,
	"agent_address_line_1" text,
	"agent_address_line_2" text,
	"agent_town" text,
	"agent_county" text,
	"agent_postcode" text,
	"agent_country" text,
	"rs_process_customs_clearance" boolean DEFAULT false,
	"agent_in_dover" text,
	"vat_dan_authority" boolean DEFAULT false,
	"postpone_vat_payment" boolean DEFAULT false,
	"clearance_agent_details" text,
	"default_delivery_address" text,
	"default_suppliers_name" text,
	"booking_in_details" text
);
--> statement-breakpoint
CREATE TABLE "import_shipments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_ref" integer NOT NULL,
	"job_type" text DEFAULT 'import' NOT NULL,
	"created_at" text DEFAULT CURRENT_DATE NOT NULL,
	"status" text DEFAULT 'Pending' NOT NULL,
	"import_customer_id" varchar,
	"import_date_eta_port" text,
	"port_of_arrival" text,
	"trailer_or_container_number" text,
	"departure_country" text,
	"container_shipment" boolean DEFAULT false,
	"vessel_name" text,
	"incoterms" text,
	"number_of_pieces" text,
	"packaging" text,
	"weight" text,
	"cube" text,
	"goods_description" text,
	"invoice_value" text,
	"freight_charge" text,
	"clearance_charge" text,
	"currency" text,
	"additional_commodity_codes" integer,
	"vat_zero_rated" boolean DEFAULT false,
	"clearance_type" text,
	"customs_clearance_agent" text,
	"rs_to_clear" boolean DEFAULT false,
	"customer_reference_number" text,
	"delivery_address" text,
	"supplier_name" text,
	"attachments" text,
	"linked_clearance_id" varchar
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
