-- Backup for export_customers
-- 20 records
-- Generated: 2025-10-10T09:36:55.696Z

INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'b859c057-5cd4-43e9-983a-30176a322f60', NULL, E'Dominick Hunter Parker Hannifin', NULL, E'366 9914 00', E'0191 402 9000', NULL, NULL, E'Team Valley Trading Est.,\nGateshead,\nTyne & Wear,\nNE11 0PZ,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'b30900a7-52b4-47da-823b-d40dec1c9509', NULL, E'Foster Refrigeration UK Ltd', NULL, E'792 4414 16', E'01553 768409', NULL, NULL, E'Oldmedow Road,\nKings Lynn,\nNorfolk,\nPE30 4JU,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'3a9020fa-e8cf-4b79-a319-a614a8a868af', NULL, E'Sauven Marking Ltd', NULL, E'413 9763 40', E'01932 355191', NULL, NULL, E'Wintersells Road,\nByfleet,\nSurrey,\nKT14 7LF,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'209d8fae-6ede-4abd-893f-2a823235aa34', NULL, E'Funktion One Research Ltd', NULL, E'724 6412 47', E'01306 712820', NULL, NULL, E'Hoyle,\nHorsham Road, Beare Green,\nDorking,\nSurrey,\nRH5 4PS,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'78d6a72d-78d9-4921-a41c-6b3159e6d0d3', NULL, E'Clement Clarke International', NULL, E'638 1946 12', E'01279 414969', NULL, NULL, E'Edinburgh Way,\nHarlow,\nEssex,\nCM20 2TT,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'd1f4d6de-7dac-4177-97fa-b5810539297c', NULL, E'Hendrickson Europe Ltd', NULL, E'581 2625 42', E'01604 493161', NULL, NULL, E'Sywell Airport,\nNorthampton,\nNN6 0BN,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'fa2b079d-0b5a-4f9b-92ee-bd0324a6a415', NULL, E'Fluorochem Ltd', NULL, E'693 4408 13', E'01457 868921', NULL, NULL, E'Wesley Street,\nOld Glossop,\nDerbyshire,\nSK13 7RY,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'aa80ed4c-b92a-44dc-b35d-8611d2ae7829', NULL, E'CCL Stressing Systems Ltd', NULL, E'734 6453 26', E'0113 270 1221', NULL, NULL, E'Unit 4 Park 2000,\nMillennium Way,\nLeeds,\nLS11 5AL,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'bb67b968-cfc1-489f-a7e5-60e5e8a41513', NULL, E'HPI Europe Ltd', NULL, E'715 8951 08', E'01283 229400', NULL, NULL, E'21 William Nadin Way,\nSwadlincote,\nDerbyshire,\nDE11 0BB,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'508a06e8-c078-422d-9ebf-47e6b494a217', NULL, E'Deloro Stellite', NULL, E'685 6063 06', E'01793 498500', NULL, NULL, E'Unit 103,,\nCheney Manor Ind Estate,\nSwindon,\nWiltshire,\nSN2 2PW,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'fd7ae831-e5fb-4d70-bfce-295b58280d8e', NULL, E'Dominick Hunter Parker Hannifin', NULL, E'366 9914 00', E'0191 402 9000', NULL, NULL, E'Team Valley Trading Est.,\nGateshead,\nTyne & Wear,\nNE11 0PZ,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'1968e45a-aea4-48b5-a641-e863051aad1f', NULL, E'Foster Refrigeration UK Ltd', NULL, E'792 4414 16', E'01553 768409', NULL, NULL, E'Oldmedow Road,\nKings Lynn,\nNorfolk,\nPE30 4JU,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'9698b62b-88e0-4534-98dd-064220ac3007', NULL, E'Sauven Marking Ltd', NULL, E'413 9763 40', E'01932 355191', NULL, NULL, E'Wintersells Road,\nByfleet,\nSurrey,\nKT14 7LF,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'95871f56-204b-46b9-a4cd-9daf5b08f642', NULL, E'Funktion One Research Ltd', NULL, E'724 6412 47', E'01306 712820', NULL, NULL, E'Hoyle,\nHorsham Road, Beare Green,\nDorking,\nSurrey,\nRH5 4PS,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'df5957d6-f32a-48cd-8211-573d546eabef', NULL, E'Clement Clarke International', NULL, E'638 1946 12', E'01279 414969', NULL, NULL, E'Edinburgh Way,\nHarlow,\nEssex,\nCM20 2TT,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'09301712-cfcb-4007-ba7e-89b0e095b418', NULL, E'Hendrickson Europe Ltd', NULL, E'581 2625 42', E'01604 493161', NULL, NULL, E'Sywell Airport,\nNorthampton,\nNN6 0BN,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'66f23484-5dc2-4dcd-ae3e-b33611799239', NULL, E'Fluorochem Ltd', NULL, E'693 4408 13', E'01457 868921', NULL, NULL, E'Wesley Street,\nOld Glossop,\nDerbyshire,\nSK13 7RY,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'2e63cd7e-c6a9-48bb-8e5a-931711603ead', NULL, E'CCL Stressing Systems Ltd', NULL, E'734 6453 26', E'0113 270 1221', NULL, NULL, E'Unit 4 Park 2000,\nMillennium Way,\nLeeds,\nLS11 5AL,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'fb85a8a5-5d49-4256-9e49-729a37ddd897', NULL, E'HPI Europe Ltd', NULL, E'715 8951 08', E'01283 229400', NULL, NULL, E'21 William Nadin Way,\nSwadlincote,\nDerbyshire,\nDE11 0BB,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO export_customers ("id", "created_by", "company_name", "contact_name", "vat_number", "telephone", "email", "accounts_email", "address", "agent_name", "agent_contact_name", "agent_vat_number", "agent_telephone", "agent_email", "agent_accounts_email", "agent_address") VALUES (E'9ddb11a1-fdca-4186-b569-80f3e0a07f90', NULL, E'Deloro Stellite', NULL, E'685 6063 06', E'01793 498500', NULL, NULL, E'Unit 103,,\nCheney Manor Ind Estate,\nSwindon,\nWiltshire,\nSN2 2PW,\nEngland', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

